# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allowfun <- function(lu, hist, codes, changedir, rules) {
    .Call('_lulcc2_allowfun', PACKAGE = 'lulcc2', lu, hist, codes, changedir, rules)
}

autoconvert <- function(lu, mask, prob, codes) {
    .Call('_lulcc2_autoconvert', PACKAGE = 'lulcc2', lu, mask, prob, codes)
}

inC <- function(x, table) {
    .Call('_lulcc2_inC', PACKAGE = 'lulcc2', x, table)
}

orderC <- function(x, decreasing) {
    .Call('_lulcc2_orderC', PACKAGE = 'lulcc2', x, decreasing)
}

ordered <- function(lu0, tprob, dmd, alloc_order, categories, stochastic, maxiter) {
    .Call('_lulcc2_ordered', PACKAGE = 'lulcc2', lu0, tprob, dmd, alloc_order, categories, stochastic, maxiter)
}

updatehist <- function(lu0, lu1, hist) {
    .Call('_lulcc2_updatehist', PACKAGE = 'lulcc2', lu0, lu1, hist)
}

